export const CARD_BG = [
  { id: 1, bgcolor: "linear-gradient(135deg, #e6f8f3 0%, #f7fcfa 100%)" },
  { id: 2, bgcolor: "linear-gradient(135deg, #fef9e7 0%, #fffdf4 100%)" },
  { id: 3, bgcolor: "linear-gradient(135deg, #eaf7ff 0%, #f3fbff 100%)" },
  { id: 4, bgcolor: "linear-gradient(135deg, #fff2e9 0%, #fff8f3 100%)" },
  { id: 5, bgcolor: "linear-gradient(135deg, #e7f6fe 0%, #f4fafd 100%)" },
  { id: 6, bgcolor: "linear-gradient(135deg, #f5f5f5 0%, #fbfbfb 100%)" },
  { id: 7, bgcolor: "linear-gradient(135deg, #fff4fc 0%, #fff8fd 100%)" },
  { id: 8, bgcolor: "linear-gradient(135deg, #e8fef3 0%, #f5fef8 100%)" },
  { id: 9, bgcolor: "linear-gradient(135deg, #f0ecff 0%, #f7f5ff 100%)" },
  { id: 10, bgcolor: "linear-gradient(135deg, #fef2f2 0%, #fff8f8 100%)" },
];

export const APP_FEATURES = [
  {
    id: 1,
    title: "AI-Powered Questions",
    description:
      "Get personalized interview questions generated by advanced AI based on your role, experience, and focus areas.",
  },
  {
    id: 2,
    title: "Video Tutorials",
    description:
      "Access curated YouTube video tutorials for each question to enhance your learning with visual explanations.",
  },
  {
    id: 3,
    title: "Free Course Recommendations",
    description:
      "Discover handpicked free online courses and resources to deepen your knowledge on interview topics.",
  },
  {
    id: 4,
    title: "Smart Explanations",
    description:
      "Get detailed, beginner-friendly explanations for complex concepts with code examples and practical insights.",
  },
  {
    id: 5,
    title: "Progress Tracking",
    description:
      "Track your interview preparation progress with pinned questions, difficulty levels, and learning analytics.",
  },
  {
    id: 6,
    title: "Role-Specific Content",
    description:
      "Content tailored to your specific job role, experience level, and technical requirements.",
  },
];
